name: pin
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

baseurl: "/pin-web-NEW2016" # the subpath of your site, e.g. /blog

index:
  de:
  en: en/index.html

nav:
# de
 - language: de
   index: /
   links:

    - ref: about
      title: Über uns
      href: about

    - ref: projects
      title: Projekte
      href: projects

    - ref: participate
      title: Mitmachen
      href: participate

    - ref: newsletter
      title: Newsletter
      href: newsletter

    - ref: contact
      title: Kontakt
      href: contakt

# en
 - language: en
   index: /en
   links:

    - ref: about
      title: About us
      href: about

    - ref: projects
      title: Projects
      href: projects

    - ref: participate
      title: Participate
      href: participate

    - ref: newsletter
      title: Newsletter
      href: newsletter

    - ref: contact
      title: Contact
      href: contact


 # en:
 #  about:
 #   title: About us
 #   href: about_us
 #  projects:
 #   title: Projects
 #   href: projects
